-- 1. 예매를 취소했을 때 예매 가능 좌석을 수정하는 트리거를 추가하고 확인.
-- 1번 서진풀이
USE CGV;
DROP TRIGGER IF EXISTS UPDATE_TICKETING;
DELIMITER //
CREATE TRIGGER UPDATE_TICKETING AFTER UPDATE
ON TICKETING
FOR EACH ROW 
BEGIN
-- 티켓 수량 변경
	IF NEW.TI_AMOUNT = OLD.TI_AMOUNT THEN 
		UPDATE screen_schedule 
			SET SS_POSSIBLE_SEAT = SS_POSSIBLE_SEAT + OLD.TI_AMOUNT
		WHERE SS_NUM = OLD.TI_SS_NUM;
		ELSE 
			IF NEW.TI_AMOUNT != OLD.TI_AMOUNT THEN 
			UPDATE screen_schedule 
				SET SS_POSSIBLE_SEAT = SS_POSSIBLE_SEAT + OLD.TI_AMOUNT - NEW.TI_AMOUNT
		WHERE SS_NUM = OLD.TI_SS_NUM;
		END IF;
    END IF;

END //
DELIMITER ;
UPDATE TICKETING SET TI_AMOUNT = 1 WHERE TI_SS_NUM = 2;


-- 1번 강사님 풀이
DROP TRIGGER IF EXISTS DELETE_TICKETING;
DELIMITER //
CREATE TRIGGER DELETE_TICKETING BEFORE DELETE
ON TICKETING
FOR EACH ROW 
BEGIN
	-- 예매된 좌석을 삭제
	DELETE FROM TICKETING_SEAT WHERE TS_TI_NUM = OLD.TI_NUM;
    -- 예매 가능 좌석수를 증가
    UPDATE SCREEN_SCHEDULE SET SS_POSSIBLE_SEAT = SS_POSSIBLE_SEAT + OLD.TI_AMOUNT
		WHERE SS_NUM = OLD.TI_SS_NUM;
-- 	CALL MEMBER_MOVIE_COUNT(OLD.TI_ME_ID);
END //
DELIMITER ;
DELETE FROM TICKETING WHERE TI_NUM = 3;
SELECT * FROM TICKETING_SEAT;



