USE CGV;

DROP PROCEDURE IF EXISTS MEMBER_MOVIE_COUNT;
DELIMITER //
CREATE PROCEDURE MEMBER_MOVIE_COUNT(
	IN _id VARCHAR(20)
)
BEGIN
	-- 지역변수선언은 위에 모아줘야 함.
	DECLARE _MOVIE_COUNT INT DEFAULT 0; 
    
	WITH TICKETING_COUNT(ss_mo_num, MOVIE_TICKETING_COUNT)
		AS
		(SELECT ss_mo_num, COUNT(*) FROM ticketing
			JOIN screen_schedule ON ti_ss_num = ss_num
			WHERE ti_me_id LIKE _id
			GROUP BY ss_mo_num) -- 영화별 예매 횟수, 예매한 전체 영화 수가 아님
		SELECT @NUM := COUNT(*) FROM TICKETING_COUNT; 
		SET _MOVIE_COUNT = (SELECT @NUM);
        SELECT _MOVIE_COUNT;
        UPDATE MEMBER SET ME_MOVIE_COUNT = _MOVIE_COUNT WHERE ME_ID = _ID;
END //
DELIMITER ;
CALL MEMBER_MOVIE_COUNT('abc');
